const cs = {
  label: 'Čeština',
  locale: 'cs-CZ',
  header: {
    subtitle: 'Kolorimetr pro kalibraci kina',
    referenceInDiagram: 'Reference v diagramu',
  },
  device: {
    connected: 'Měřák připojen',
    disconnected: 'Měřák odpojen',
    probing: 'Zjišťuji…',
  },
  measurement: {
    title: 'Měření',
    luminance: 'Jas',
    waiting: 'Čekám na data',
    saturation: 'Saturace',
    acquiring: 'Ustaluji…',
    stable: 'Stabilní',
    fluctuating: 'Kolísá',
    inTolerance: 'v toleranci',
    marginal: 'hraniční',
    out: 'mimo',
    cct: 'Teplota chromatičnosti',
    toggleUnit: 'Přepnout jednotku jasu',
  },
  dci: {
    title: 'Shoda DCI/SMPTE',
    target: 'Cíl',
    pass: 'Vyhovuje',
    marginal: 'Hraniční',
    out: 'Mimo toleranci',
    informative: 'Informativní',
    informativeLower: 'informativní',
    aim: 'Namiřte měřák na kalibrační barvu',
    color: 'Barva',
  },
  targets: {
    white: 'bílá',
    red: 'červená',
    green: 'zelená',
    blue: 'modrá',
    cyan: 'azurová',
    magenta: 'purpurová',
    yellow: 'žlutá',
  },
  reference: {
    label: 'Reference',
    custom: 'Vlastní',
    whiteX: 'bílá x',
    whiteY: 'bílá y',
    lumFtl: 'jas (fL)',
  },
  controls: {
    title: 'Ovládání',
    live: 'Živě',
    offline: 'Odpojeno',
    startScan: 'Spustit sken',
    stopScan: 'Zastavit sken',
    measureDark: 'Změřit dark',
    clearDark: 'Zrušit dark',
    darkActive: 'Aktivní runtime dark: odečítá se místo kalibračního modelu.',
    averaging: 'Průměrování',
    averagingDetail: '8 skenů',
    integration: 'Integrační čas',
    serial: 'Sériové číslo',
  },
  cie: {
    title: 'Chromatický diagram CIE 1931',
    aria: 'Chromatický diagram CIE 1931 s naměřeným bodem',
  },
  spectrum: {
    title: 'Spektrum (nm)',
    integration: 'Integrační čas',
    empty: 'Spektrum není k dispozici',
    aria: 'Spektrální rozložení',
  },
  history: {
    title: 'Historie měření',
    clear: 'Vymazat',
    export: 'Exportovat CSV',
    exported: 'Uloženo',
    exportError: 'Export selhal',
    placeholder: 'Název měření',
    notePlaceholder: 'Poznámka (volitelná)',
    save: 'Uložit měření',
    name: 'Název',
    note: 'Poznámka',
    time: 'Čas',
    empty: 'Zatím žádná uložená měření',
    defaultLabel: 'Měření',
  },
  footer: {
    developer: 'Vývojář',
    tagline: 'Digitální kino & AV technologie · XC tech s.r.o.',
    appDesc: 'PCA-100 · kolorimetr pro kalibraci jasu a barevného prostoru kinosálu.',
  },
  update: {
    badge: 'Aktualizace',
    title: 'Je dostupná aktualizace',
    description: 'Nová verze PCA-100 je připravena ke stažení.',
    releaseNotes: 'Poznámky k vydání',
    download: 'Stáhnout a nainstalovat',
    downloading: 'Stahuji…',
    downloaded: 'Instalátor otevřen. Přetáhněte PCA-100 do složky Aplikace a spusťte znovu.',
    error: 'Stažení se nezdařilo.',
  },
  remote: {
    trigger: 'Vzdálený přístup',
    title: 'Vzdálený přístup',
    description: 'Povolte přístup k měřáku z jiných zařízení ve stejné síti.',
    toggle: 'Povolit přístup z jiných zařízení',
    caution: 'Pozor: kdokoliv v této síti může měřák vidět a ovládat.',
    urlsTitle: 'Připojte se na',
    qrAlt: 'QR kód pro připojení',
    empty: 'Vzdálený přístup je vypnutý.',
    noUrls: 'Nenalezena žádná síťová adresa. Zkontrolujte připojení Wi-Fi.',
  },
}

export type Strings = typeof cs

const en: Strings = {
  label: 'English',
  locale: 'en-US',
  header: {
    subtitle: 'Cinema calibration colorimeter',
    referenceInDiagram: 'Reference in diagram',
  },
  device: {
    connected: 'Meter connected',
    disconnected: 'Meter disconnected',
    probing: 'Probing…',
  },
  measurement: {
    title: 'Measurement',
    luminance: 'Luminance',
    waiting: 'Waiting for data',
    saturation: 'Saturated',
    acquiring: 'Acquiring…',
    stable: 'Stable',
    fluctuating: 'Fluctuating',
    inTolerance: 'in tolerance',
    marginal: 'marginal',
    out: 'out',
    cct: 'Correlated color temp.',
    toggleUnit: 'Toggle luminance unit',
  },
  dci: {
    title: 'DCI/SMPTE compliance',
    target: 'Target',
    pass: 'Pass',
    marginal: 'Marginal',
    out: 'Out of tolerance',
    informative: 'Informative',
    informativeLower: 'informative',
    aim: 'Point the meter at a calibration color',
    color: 'Color',
  },
  targets: {
    white: 'white',
    red: 'red',
    green: 'green',
    blue: 'blue',
    cyan: 'cyan',
    magenta: 'magenta',
    yellow: 'yellow',
  },
  reference: {
    label: 'Reference',
    custom: 'Custom',
    whiteX: 'white x',
    whiteY: 'white y',
    lumFtl: 'lum (fL)',
  },
  controls: {
    title: 'Controls',
    live: 'Live',
    offline: 'Offline',
    startScan: 'Start scan',
    stopScan: 'Stop scan',
    measureDark: 'Capture dark',
    clearDark: 'Clear dark',
    darkActive: 'Runtime dark active: subtracted instead of the calibrated model.',
    averaging: 'Averaging',
    averagingDetail: '8 scans',
    integration: 'Integration time',
    serial: 'Serial number',
  },
  cie: {
    title: 'CIE 1931 chromaticity diagram',
    aria: 'CIE 1931 chromaticity diagram with the measured point',
  },
  spectrum: {
    title: 'Spectrum (nm)',
    integration: 'Integration time',
    empty: 'Spectrum not available',
    aria: 'Spectral distribution',
  },
  history: {
    title: 'Measurement history',
    clear: 'Clear',
    export: 'Export CSV',
    exported: 'Saved',
    exportError: 'Export failed',
    placeholder: 'Measurement name',
    notePlaceholder: 'Note (optional)',
    save: 'Save measurement',
    name: 'Name',
    note: 'Note',
    time: 'Time',
    empty: 'No saved measurements yet',
    defaultLabel: 'Measurement',
  },
  footer: {
    developer: 'Developer',
    tagline: 'Digital cinema & AV technology · XC tech s.r.o.',
    appDesc: 'PCA-100 · colorimeter for auditorium luminance and color space calibration.',
  },
  update: {
    badge: 'Update',
    title: 'Update available',
    description: 'A new version of PCA-100 is ready to download.',
    releaseNotes: 'Release notes',
    download: 'Download and install',
    downloading: 'Downloading…',
    downloaded: 'Installer opened. Drag PCA-100 to Applications and relaunch.',
    error: 'Download failed.',
  },
  remote: {
    trigger: 'Remote access',
    title: 'Remote access',
    description: 'Allow the meter to be accessed from other devices on the same network.',
    toggle: 'Allow access from other devices',
    caution: 'Caution: anyone on this network can view and control the meter.',
    urlsTitle: 'Connect at',
    qrAlt: 'Connect QR',
    empty: 'Remote access is off.',
    noUrls: 'No network address found. Check your Wi-Fi connection.',
  },
}

export const STRINGS = { cs, en } as const
